AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DpaasCloudFormationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: DpaasCloudFormationPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:ListStacks'
                  - 'cloudformation:RollbackStack'
                  - 'eks:CreateCluster'
                  - 'eks:CreateNodegroup'
                  - 'eks:DeleteCluster'
                  - 'eks:DeleteNodegroup'
                  - 'eks:DescribeCluster'
                  - 'eks:DescribeNodegroup'
                  - 'eks:ListClusters'
                  - 'eks:ListNodegroups'
                  - 'eks:TagResources'
                  - 'eks:UntagResources'
                  - 'ec2:AssociateIamInstanceProfile'
                  - 'ec2:DescribeInstances'
                  - 'ec2:DisassociateIamInstanceProfile'
                  - 'ec2:StartInstances'
                  - 'ec2:StopInstances'
                  - 'ec2:RebootInstances'
                  - 'ec2:TerminateInstances'
                  - 'ec2:CreateLaunchTemplate'
                  - 'ec2:DeleteLaunchTemplate'
                  - 'ec2:DescribeLaunchTemplate'
                  - 'ec2:ModifyLaunchTemplate'
                  - 'ec2:CreateSecurityGroup'
                  - 'ec2:DeleteSecurityGroup'
                  - 'ec2:ModifySecurityGroupRules'
                  - 'ec2:DescribeSecurityGroup'
                  - 'kms:CreateKeyPair'
                  - 'kms:DeleteKeyPair'
                  - 'tagging:TagResource'
                  - 'tagging:UntagResource'
                Resource: '*'
  DpaasCloudFormationInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref DpaasCloudFormationRole

Outputs:
  DpaasCloudFormationRoleArn:
    Value: !GetAtt DpaasCloudFormationRole.Arn
    Description: ARN of the IAM Role created for CloudFormation