---
AWSTemplateFormatVersion: 2010-09-09
Description: Amazon EKS - Node Group
Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: String
  NodeInstanceType:
    Description: EC2 instance type for the node instances
    Type: String
  NodeVolumeSize:
    Description: Node volume size
    Type: Number
    Default: 20
  ClusterName:
    Description: >-
      The cluster name provided when the cluster was created. If it is
      incorrect, nodes will not be able to join the cluster.
    Type: String
  NodeGroupName:
    Description: Unique identifier for the Node Group.
    Type: String
  NodeGroupRole:
    Description: ARN of node group role
    Type: String
  ControlPlaneSecurityGroup:
    Description: The security group of the cluster control plane.
    Type: 'AWS::EC2::SecurityGroup::Id'
  WorkerSecurityGroup:
    Description: Additional security group to grant to worker nodes.
    Type: 'AWS::EC2::SecurityGroup::Id'
  BastionSecurityGroup:
    Description: Additional security group to grant to worker nodes.
    Type: 'AWS::EC2::SecurityGroup::Id'
  VpcId:
    Description: The VPC of the worker instances
    Type: 'AWS::EC2::VPC::Id'
  VpcCidr:
    Description: The CIDR of the VPC for the worker instances
    Type: String
  Subs:
    Description: The subnets where workers can be created.
    Type: String

Resources:
  NodeGroup:
    Type: AWS::EKS::Nodegroup
    DependsOn: "EKSCluster"
    Properties:
      AmiType: AL2_x86_64
      ClusterName: !Ref ClusterName
      DiskSize: !Ref NodeVolumeSize
      InstanceTypes: !Ref NodeInstanceType
      NodeRole: !Ref NodeGroupRole
      RemoteAccess:
        Ec2SshKey: !Ref KeyName
        SourceSecurityGroups: !Ref BastionSecurityGroup
      ScalingConfig:
        DesiredSize: 2
        MaxSize: 3
        MinSize: 1
      Subnets:
        Fn::Split: [" ", !Ref Subs]
