---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Foundation for nested stacks"

Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: String
  ClusterName:
    Description: >-
      The cluster name provided when the cluster was created. If it is
      incorrect, nodes will not be able to join the cluster.
    Type: String
  ClusterRoleArn:
    Description: EKS Role ARN
    Type: String
  BastionInstanceType:
    Description: EC2 instance type for the bastion host
    Type: String
  AMI:
    Description: EC2 instance type for the bastion host
    Type: String
  BastionName:
    Description: EC2 instance type for the bastion host
    Type: String
  BastionSecurityGroupName:
    Description: EC2 instance type for the bastion host
    Type: String

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformation-bucket-04022024.s3.us-gov-west-1.amazonaws.com/vpc-stack.yaml
      Tags:
        - Key: Name
          Value: "nested-vpc-stack"

  ClusterStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VpcStack
    Properties:
      TemplateURL: https://cloudformation-bucket-04022024.s3.us-gov-west-1.amazonaws.com/cluster-stack.yaml
      Parameters:
        KeyName: !Ref KeyName
        ClusterName: !Ref ClusterName
        ClusterRoleArn: !Ref ClusterRoleArn
        Subs: !GetAtt VpcStack.Outputs.WorkerSubnetIds

  BastionStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ClusterStack
    Properties:
      TemplateURL: https://cloudformation-bucket-04022024.s3.us-gov-west-1.amazonaws.com/bastion-stack.yaml
      Parameters:
        AMI: !Ref AMI
        KeyName: !Ref KeyName
        BastionName: !Ref BastionName
        ClusterName: !Ref ClusterName
        ClusterRoleArn: !Ref ClusterRoleArn
        BastionInstanceType: !Ref BastionInstanceType
        BastionSecurityGroupName: !Ref BastionSecurityGroupName
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        Subnet: !GetAtt VpcStack.Outputs.BastionSubnetId
        ClusterControlPlaneSecurityGroup: !GetAtt ClusterStack.Outputs.ControlPlaneSecurityGroup

