---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EC2'

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
  KeyPair:
    Type: String
    Default: martin-test
  AMI:
    Type: String
    Default: ami-04306748291e2183c
    Description: Latest RHEL 7 spel-minimal image
  Subnet:
    Type: String
    Description: Public subnet 1a
    Default: subnet-0df573ca6ba163dc2
  SG:
    Type: String
    Default: sg-01c829f8d3686ab8d

Resources:
  MartinBastion:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !Ref AMI # Specify your desired AMI ID
      KeyName: !Ref KeyPair  # Specify the name of your existing key pair
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 100  # Size of the root volume in GiBs
            VolumeType: gp2  # Specify the volume type (e.g., gp2, io1, st1, sc1)
      SubnetId: !Ref Subnet
      SecurityGroupIds: 
      - !Ref SG
      Tags:
      - Key: Name
        Value: EKS-Bastion
      - Key: Env
        Value: Dev
      

Outputs:
  InstanceId:
    Description: The instance ID of the EC2 instance
    Value: !Ref MartinBastion
  AMI:
    Value: !Ref AMI
  IP:
    Value: !GetAtt MartinBastion.PublicIp
  

